theme: minima
title: "MadaLog"
description: "О чем угодно пишу."
url: "https://danbuyt.github.io"
baseurl: ""

permalink: /:year/:month/:day/:title/
timezone: Europe/Kaliningrad

author:
  name: "Dan"
  email: "dana33topo@gmail.com"
sass:
sass_dir: assets/css/style.scss
