title: "Mada Log"
description: "Пишу всякое разное"
url: "https://danbuyt.github.io" 
baseurl: ""


permalink: /:year/:month/:day/:title/
timezone: Europe/Kaliningrad


author:
  name: "Dan"
  email: "dana33topo@gmail.com"
